# Generated by Django 3.2 on 2021-05-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_villa', '0003_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
